apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-cocktail
    version: 2
    type: postgres
    access: proxy
    url: postgres:5432
    database: cocktail_assistant
    user: user
    isDefault: true
    secureJsonData:
      password: password
    jsonData:
      database: cocktail_assistant
      sslmode: disable
      postgresVersion: 1700
